/**
 * NeutralWire Google Discover — resource pack registry.
 *
 * Every resource the owner needs to execute the Discover plan, as pure
 * data (safe to import from client components — no FS access). Rendered
 * by the /debug Discover Kit's Resources tab: expandable viewer, copy,
 * and download-as-file (client Blob — no server zip endpoint needed).
 *
 * `repoPath` (when set) is where the SAME content lives in the repository
 * so the repo and the Kit can never drift silently apart.
 */

export interface DiscoverResource {
  id: string
  title: string
  description: string
  filename: string
  language: string
  category: 'code' | 'config' | 'doc' | 'script'
  repoPath?: string
  content: string
}

const LINES = (arr: string[]) => arr.join('\n')

export const DISCOVER_RESOURCES: DiscoverResource[] = [
  {
    id: 'robots',
    title: 'robots.txt (as shipped)',
    description:
      'Crawl rules with the sitemaps re-enabled — AI-crawler blocks preserved exactly as they were. Drop into public/robots.txt (already deployed with the kit).',
    filename: 'robots.txt',
    language: 'txt',
    category: 'config',
    repoPath: 'public/robots.txt',
    content: LINES([
      '# Search engines (ALLOWED — they help with SEO)',
      'User-agent: Googlebot',
      'Allow: /',
      '',
      'User-agent: Bingbot',
      'Allow: /',
      '',
      'User-agent: Twitterbot',
      'Allow: /',
      '',
      'User-agent: facebookexternalhit',
      'Allow: /',
      '',
      'User-agent: LinkedInBot',
      'Allow: /',
      '',
      'User-agent: WhatsApp',
      'Allow: /',
      '',
      'User-agent: TelegramBot',
      'Allow: /',
      '',
      '# …AI crawlers stay blocked exactly as before (GPTBot, ClaudeBot,',
      '#  CCBot, PerplexityBot, Bytespider, etc.)…',
      '',
      '# Default: allow everything else',
      'User-agent: *',
      'Allow: /',
      '',
      '# Sitemaps — safe to list again since the 6.2GB Firebase fix:',
      '#   /sitemap.xml      is fully static (zero Firebase reads)',
      '#   /news-sitemap.xml does ONE ETag-cached read per regeneration',
      'Sitemap: https://neutralwire.org/sitemap.xml',
      'Sitemap: https://neutralwire.org/news-sitemap.xml',
    ]),
  },
  {
    id: 'robots-meta',
    title: 'The Discover gate — robots meta snippet',
    description:
      'The single most important line of the whole programme: max-image-preview:large tells Google it may use LARGE images in Discover cards. Already live in src/app/layout.tsx — this is the exact block, for reference/verification.',
    filename: 'layout-robots-meta.ts',
    language: 'ts',
    category: 'code',
    repoPath: 'src/app/layout.tsx (metadata.robots)',
    content: LINES([
      'export const metadata: Metadata = {',
      '  // …',
      '  robots: {',
      '    index: true,',
      '    follow: true,',
      '    googleBot: {',
      '      index: true,',
      '      follow: true,',
      "      'max-image-preview': 'large',",
      "      'max-snippet': -1,",
      "      'max-video-preview': -1,",
      '    },',
      '  },',
      '  // …',
      '}',
      '',
      '// Renders as:',
      '// <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">',
      '// <meta name="googlebot" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">',
      '',
      '// ⚠ Pages must NOT set their own `robots` key — page metadata',
      '// shallow-replaces the layout value and would drop the gate.',
    ]),
  },
  {
    id: 'news-sitemap',
    title: '/news-sitemap.xml route (as shipped)',
    description:
      'Google News sitemap listing stories from the last 48 hours, each with publication info + image:image (the card-image signal). One ETag-cached Firebase read per regeneration; 15-minute CDN caching.',
    filename: 'news-sitemap.xml-route.ts',
    language: 'ts',
    category: 'code',
    repoPath: 'src/app/news-sitemap.xml/route.ts',
    content: LINES([
      "import { NextRequest, NextResponse } from 'next/server'",
      "import { readCachedNews } from '@/lib/news-cache'",
      "import { SITE_URL } from '@/lib/site'",
      '',
      "export const runtime = 'nodejs'",
      "export const dynamic = 'force-dynamic'",
      '',
      'const FRESH_WINDOW_MS = 48 * 60 * 60 * 1000 // Google News sitemap: ≤48h',
      "const CDN_CACHE = 'public, s-maxage=900, stale-while-revalidate=3600'",
      '',
      'export async function GET(req: NextRequest) {',
      "  const payload = await readCachedNews('top') // ONE ETag-cached read",
      '  const urls = (payload?.topics || [])',
      '    .filter((t) => Date.now() - (t.latestSeen || 0) <= FRESH_WINDOW_MS)',
      '    .map((t) => {',
      '      const loc = `${SITE_URL}/story/${encodeURIComponent(t.topicId)}`',
      '      const img = t.imageUrl',
      '        ? `    <image:image>\\n      <image:loc>${SITE_URL}/api/img?url=${encodeURIComponent(t.imageUrl)}</image:loc>\\n    </image:image>`',
      "        : ''",
      '      return [',
      '        ' + "'  <url>'",
      '        ' + "'    <loc>' + loc + '</loc>'",
      '        ' + "'    <news:news>'",
      '        ' + "'      <news:publication>'",
      '        ' + "'        <news:name>NeutralWire</news:name>'",
      '        ' + "'        <news:language>en</news:language>'",
      '        ' + "'      </news:publication>'",
      '        ' + "'      <news:publication_date>' + new Date(t.latestSeen).toISOString() + '</news:publication_date>'",
      '        ' + "'      <news:title>' + escapeXml(t.title) + '</news:title>'",
      '        ' + "'    </news:news>'",
      '        img,',
      '        ' + "'  </url>'",
      '      ].filter(Boolean).join("\\n")',
      '    }).join("\\n")',
      '',
      '  const xml = `<?xml version="1.0" encoding="UTF-8"?>',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
      '        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"',
      '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
      '${urls}',
      '</urlset>`',
      '',
      '  return new NextResponse(xml, {',
      '    headers: {',
      "      'Content-Type': 'application/xml; charset=utf-8',",
      `      'Cache-Control': CDN_CACHE,`,
      `      ETag: '"nw-news-' + (payload?.updatedAt || 0) + '"',`,
      '    },',
      '  })',
      '}',
    ]),
  },
  {
    id: 'rss',
    title: '/feed.xml — RSS 2.0 route (as shipped)',
    description:
      'The Publisher Center feed: real titles, summaries, RFC-822 dates and STABLE GUIDs (topicId — the same id /story/<id> serves). Zero-drift between feed items and article URLs.',
    filename: 'feed.xml-route.ts',
    language: 'ts',
    category: 'code',
    repoPath: 'src/app/feed.xml/route.ts',
    content: LINES([
      "import { NextRequest, NextResponse } from 'next/server'",
      "import { readCachedNews } from '@/lib/news-cache'",
      "import { SITE_URL } from '@/lib/site'",
      '',
      "export const runtime = 'nodejs'",
      "export const dynamic = 'force-dynamic'",
      '',
      'const rfc822 = (ts: number) => new Date(ts).toUTCString()',
      'const cdata = (s: string) => `<![CDATA[${s.replace(/]]>/g, "]]&gt;")}]]>`',
      '',
      'export async function GET(req: NextRequest) {',
      "  const payload = await readCachedNews('top') // ONE ETag-cached read",
      '  const items = (payload?.topics || []).slice(0, 30).map((t) => [',
      "    '<item>',",
      "    '<title>' + cdata(t.title) + '</title>',",
      "    '<link>' + SITE_URL + '/story/' + encodeURIComponent(t.topicId) + '</link>',",
      '    \'<guid isPermaLink="false">\' + t.topicId + \'</guid>\',',
      "    '<pubDate>' + rfc822(t.latestSeen || t.firstSeen) + '</pubDate>',",
      "    '<description>' + cdata(t.summary || t.title) + '</description>',",
      "  ].join('')).join('\\n')",
      '',
      '  const xml = `<?xml version="1.0" encoding="UTF-8"?>',
      '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">',
      '  <channel>',
      '    <title>NeutralWire</title>',
      '    <link>${SITE_URL}</link>',
      '    <description>How left, centre and right outlets cover the SAME story — side by side.</description>',
      '    <language>en</language>',
      '    <lastBuildDate>${rfc822(payload?.updatedAt || Date.now())}</lastBuildDate>',
      '    <docs>https://www.rssboard.org/rss-specification</docs>',
      '    <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml"/>',
      '    ${items}',
      '  </channel>',
      '</rss>`',
      '',
      "  const etag = '\"nw-feed-' + (payload?.updatedAt || 0) + '\"'",
      "  if (req.headers.get('if-none-match') === etag) {",
      '    return new NextResponse(null, { status: 304, headers: { ETag: etag } })',
      '  }',
      '  return new NextResponse(xml, {',
      '    headers: {',
      "      'Content-Type': 'application/rss+xml; charset=utf-8',",
      "      'Cache-Control': 'public, s-maxage=900, stale-while-revalidate=3600',",
      '      ETag: etag,',
      '    },',
      '  })',
      '}',
    ]),
  },
  {
    id: 'story-jsonld',
    title: 'NewsArticle JSON-LD (as shipped on /story/[id])',
    description:
      'The structured data Google reads from every story page: headline, image array, dates, NewsMediaOrganization publisher, isBasedOn provenance links to every outlet. Paste any /story URL into the Rich Results Test to validate.',
    filename: 'news-article-json-ld.ts',
    language: 'ts',
    category: 'code',
    repoPath: 'src/app/story/[id]/page.tsx (newsArticleJsonLd)',
    content: LINES([
      'const ld = {',
      "  '@context': 'https://schema.org',",
      "  '@type': 'NewsArticle',",
      '  headline: topic.title.slice(0, 110),',
      '  description: topic.summary,',
      '  image: [',
      '    // raw hero via the image proxy (real photo) …',
      `    SITE_URL + '/api/img?url=' + encodeURIComponent(topic.imageUrl),`,
      '    // …and the branded 1200x630 composite (guaranteed render)',
      `    SITE_URL + '/api/og-image?topicId=' + topic.topicId,`,
      '  ],',
      '  datePublished: new Date(topic.firstSeen).toISOString(),',
      '  dateModified: new Date(topic.latestSeen).toISOString(),',
      '  author: [{ "@type": "Organization", name: "NeutralWire", url: SITE_URL }],',
      '  publisher: {',
      '    "@type": "NewsMediaOrganization",',
      '    name: "NeutralWire",',
      '    url: SITE_URL,',
      '    logo: { "@type": "ImageObject", url: SITE_URL + "/icon-512.png" },',
      '  },',
      '  mainEntityOfPage: {',
      '    "@type": "WebPage",',
      '    "@id": SITE_URL + "/story/" + topic.topicId,',
      '  },',
      '  // Provenance — every outlet article the comparison is based on:',
      '  isBasedOn: topic.articles.slice(0, 12).map((a) => a.link),',
      '  isAccessibleForFree: true,',
      '}',
      '',
      '<script',
      '  type="application/ld+json"',
      "  dangerouslySetInnerHTML={{ __html: JSON.stringify(ld).replace(/</g, '\\\\u003c') }}",
      '/>',
    ]),
  },
  {
    id: 'publisher-checklist',
    title: 'Publisher Center — full submission checklist',
    description:
      'Step-by-step: create the publication, add /feed.xml, upload the 512×512 logo, submit for review — including the common rejection reasons and how NeutralWire already avoids each one.',
    filename: 'publisher-center-checklist.md',
    language: 'md',
    category: 'doc',
    repoPath: 'resources/discover/publisher-center-checklist.md',
    content: LINES([
      '# Google Publisher Center — submission checklist',
      '',
      'Time: ~20 min (+ days-to-weeks Google review).',
      '',
      '## Before you start',
      '- Site live on https://neutralwire.org',
      '- https://neutralwire.org/feed.xml returns valid RSS 2.0',
      '- Google account that owns the Search Console property',
      '- Publication logo: 512×512 PNG, transparent bg (public/icon-512.png works)',
      '',
      '## Steps',
      '1. publishercenter.google.com → Add publication',
      '2. Name: NeutralWire · site: neutralwire.org · language: en · primary country: main market',
      '3. Add RSS feed: https://neutralwire.org/feed.xml → category News/Politics',
      '4. Upload the 512×512 logo',
      '5. Publication info → blurb + privacy policy link (/privacy)',
      '6. Submit for review',
      '7. After approval: re-check feed health monthly (Kit → Readiness tab)',
      '',
      '## Common rejections — already mitigated',
      '| Reason | NeutralWire status |',
      '|---|---|',
      '| Feed empty/malformed | full-content RSS, cron-refreshed |',
      '| No publication identity | NewsMediaOrganization JSON-LD + logo |',
      '| Aggregator w/o value | left/centre/right comparison IS the value |',
      '| Clickbait/deceptive | titles from real outlets, cleaned at ingest |',
      '| Rotting links | topics archived on first view |',
    ]),
  },
  {
    id: 'gsc-script',
    title: 'Bulk URL Inspection script',
    description:
      'Bun/Node script using the Search Console URL Inspection API: pulls the newest /story URLs from the news sitemap and reports index coverage for each (2,000/day quota). Env-keyed OAuth, no secrets in the repo.',
    filename: 'gsc-url-inspection.ts',
    language: 'ts',
    category: 'script',
    repoPath: 'resources/discover/gsc-url-inspection.ts',
    content: LINES([
      "// bun resources/discover/gsc-url-inspection.ts  (bun add googleapis)",
      "import { google } from 'googleapis'",
      '',
      "const SITE_URL = process.env.SITE_URL || 'https://neutralwire.org'",
      "const LIMIT = Number(process.env.LIMIT || '25')",
      '',
      'async function storyUrls() {',
      '  const xml = await (await fetch(`${SITE_URL}/news-sitemap.xml`)).text()',
      '  return [...xml.matchAll(/<loc>([^<]+\\/story\\/[^<]+)<\\/loc>/g)]',
      '    .map((m) => m[1]).slice(0, LIMIT)',
      '}',
      '',
      'async function main() {',
      '  const oauth = new google.auth.OAuth2({',
      '    clientId: process.env.GSC_CLIENT_ID,',
      '    clientSecret: process.env.GSC_CLIENT_SECRET,',
      "    redirectUri: 'urn:ietf:wg:oauth:2.0:oob',",
      '  })',
      '  const { client } = await google.discoverAPI(',
      "    'https://searchconsole.googleapis.com/$discovery/rest?version=v1',",
      '  )',
      '  for (const url of await storyUrls()) {',
      '    const res = await (client as any).urlInspection.index.inspect({',
      '      inspectionUrl: url, siteUrl: SITE_URL, languageCode: "en",',
      '    })',
      '    const state = res.data?.inspectionResult?.indexStatus?.coverageState',
      '    console.log(`${/indexed/i.test(state || "") ? "OK " : "!! "} ${state}  ${url}`)',
      '  }',
      '}',
      'main()',
    ]),
  },
  {
    id: 'content-rules',
    title: 'Discover content rules — images & headlines',
    description:
      'What earns the card: ≥1200px real photos, no placeholders, no clickbait, title↔content parity — mapped onto NeutralWire\'s image-verification and title-cleaner pipelines, plus the weekly 2-minute spot-check ritual.',
    filename: 'discover-content-rules.md',
    language: 'md',
    category: 'doc',
    repoPath: 'resources/discover/discover-content-rules.md',
    content: LINES([
      '# Discover content rules',
      '',
      '## Images',
      '- ≥1200px wide, real editorial photos — the card IS the picture',
      '- max-image-preview:large gate (shipped) + image:image in news sitemap (shipped)',
      '- og:images are vision-verified against the headline (cache v6, the "Tesco fix")',
      '- No photo → no image entry. NEVER a black/placeholder card',
      '- Composite bias-bar image is for SOCIAL previews only, not Discover cards',
      '- Weekly: open 5 fresh /story pages — heroes must be real, relevant, large',
      '',
      '## Headlines',
      '- No clickbait/teasers, no ALL-CAPS, no trailing "…", no title↔content mismatch',
      '- Titles come from real outlets, cleaned at ingest (WATCH: stripping, v7)',
      '- Story page structurally delivers the title → parity by construction',
      '- AI-fixed titles: what happened, to whom, where. 60-90 chars. Neutral core.',
      '',
      '## E-E-A-T',
      '- Experience: the product demonstrates it (side-by-side comparison)',
      '- Expertise: documented source leanings (source-ratings.ts)',
      '- Authority: NewsMediaOrganization + NewsArticle JSON-LD + outbound isBasedOn',
      '- Trust: privacy policy, no paywalls, archived permanent links',
      '',
      '## Freshness',
      '- news-sitemap = last 48h only (shipped)',
      '- feeds ≤30 min stale via cron — nothing manual',
      '- Steady trickle beats bursts (already the app rhythm)',
    ]),
  },
  {
    id: 'cron-wiring',
    title: 'Cron wiring — feed warm-up (optional)',
    description:
      'Why the new routes are already bandwidth-safe by design, and the optional 2-line fire-and-forget warm-up to append to the cron refresh handler if you want instant-fresh sitemaps. Includes the what-NOT-to-do that caused 6.2 GB.',
    filename: 'cron-wiring.md',
    language: 'md',
    category: 'doc',
    repoPath: 'resources/discover/cron-wiring.md',
    content: LINES([
      '# Cron wiring (optional feed warm-up)',
      '',
      '| Route | Firebase cost/regeneration | CDN |',
      '|---|---|---|',
      '| /sitemap.xml | ZERO (static) | 24h |',
      '| /news-sitemap.xml | 1 ETag-cached read → 0 bytes unchanged | 15 min |',
      '| /feed.xml | same | 15 min |',
      '| /story/[id] | 1 archive read, ETag-cached | 15 min ISR |',
      '',
      'Optional warm-up in api/cron/refresh-all/route.ts:',
      '  const warm = async (p: string) => {',
      "    try { await fetch(`${SITE_URL}${p}`, { cache: 'no-store' }) } catch {}",
      '  }',
      "  void warm('/news-sitemap.xml')",
      "  void warm('/feed.xml')",
      '',
      '## Do NOT',
      '- Do not remove s-maxage "to be fresher" — that path = the 6.2GB incident',
      '- Do not enumerate every story in /sitemap.xml — news sitemap is the vehicle',
    ]),
  },
  {
    id: 'monitoring',
    title: 'Discover monitoring recipe',
    description:
      'The weekly 2-minute ritual: GSC → Performance → Discover tab, plus the scripted version via the Search Analytics API with the Discover dimension.',
    filename: 'discover-monitoring.ts',
    language: 'ts',
    category: 'script',
    content: LINES([
      '// Search Analytics API — Discover performance (run weekly)',
      '// Auth: same OAuth setup as gsc-url-inspection.ts',
      'const res = await (client as any).searchanalytics.query({',
      "  siteUrl: 'https://neutralwire.org',",
      '  requestBody: {',
      "    startDate: weekAgoISO,",
      "    endDate: todayISO,",
      "    dimensions: ['page'],",
      "    searchType: 'web',",
      '    dimensionFilterGroups: [{',
      '      filters: [{ dimension: "SEARCH_APPEARANCE", expression: "DISCOVER" }],',
      '    }],',
      '    rowLimit: 25,',
      '  },',
      '})',
      '',
      '// rows[] → keys[0]=story URL, clicks, impressions, ctr, position',
      '// Watch CTR by story type → feed patterns back into titles/images',
    ]),
  },
  {
    id: 'gsc-submission',
    title: 'Search Console — sitemap submission recipe',
    description:
      'Exact steps to submit both sitemaps and request indexing for the first story URLs — the 10 minutes that seed discovery.',
    filename: 'gsc-submission.md',
    language: 'md',
    category: 'doc',
    content: LINES([
      '# Search Console submission (one-time, 10 min)',
      '',
      '1. search.google.com/search-console → property neutralwire.org (already verified)',
      '2. Sitemaps → Add a new sitemap:',
      '   - neutralwire.org/sitemap.xml        → Submit',
      '   - neutralwire.org/news-sitemap.xml   → Submit',
      '3. URL Inspection (top search bar):',
      '   - paste a /story/<id> URL → "Test Live URL" → expect "URL is available to Google"',
      '   - → "Request Indexing" (do this for 3-5 fresh stories, not more)',
      '4. Come back in a week:',
      '   - Sitemaps → "Discovered URLs" trending up?',
      '   - Pages report → /story/* pages appearing as "Indexed"?',
      '   - URL Inspection on the homepage → rendered HTML contains',
      '     max-image-preview:large?',
    ]),
  },
  {
    id: 'readme',
    title: 'README — the whole kit on one page',
    description:
      'The master index: what already ships in the app, what the owner must do, and the 15-minute path from deploy to submitted.',
    filename: 'README.md',
    language: 'md',
    category: 'doc',
    repoPath: 'resources/discover/README.md',
    content: LINES([
      '# Google Discover Kit — resource pack',
      '',
      '## What already ships',
      '| Capability | Route |',
      '|---|---|',
      '| max-image-preview:large gate | src/app/layout.tsx |',
      '| Crawlable story pages + NewsArticle | src/app/story/[id]/page.tsx |',
      '| News sitemap (≤48h) | src/app/news-sitemap.xml/route.ts |',
      '| RSS 2.0 full feed | src/app/feed.xml/route.ts |',
      '| robots.txt with sitemaps | public/robots.txt |',
      '',
      '## Owner actions',
      '1. Submit both sitemaps in Search Console',
      '2. URL-Inspect 3-5 story URLs → Request Indexing',
      '3. Publisher Center → publication + /feed.xml → submit',
      '4. Weekly: GSC Discover report review',
      '',
      'The interactive version: /debug → Discover Kit',
    ]),
  },
]

export const DISCOVER_RESOURCE_COUNT = DISCOVER_RESOURCES.length
