/**
 * subtopic-catalog.ts — the Premium custom-subtopic catalog.
 *
 * 330+ ready-to-subscribe NeutralWire subtopics ("AI", "Chess", "Mars
 * missions", "Formula 1"…), each with GDELT search keywords. The picker
 * UI searches this catalog; anything NOT in it is created on demand by
 * the AI subtopic factory (POST /api/subtopics/create) and appended to
 * the runtime catalog in Firebase (`customSubtopics/<id>`).
 *
 * Compact format: "Label|keyword,keyword,…" parsed once at module load.
 * Keywords are lowercase GDELT-friendly terms (quoted + OR-joined when
 * the feed refresh queries GDELT — see lib/custom-topics.ts).
 */

export interface CatalogTopic {
  id: string
  label: string
  keywords: string[]
  group: string
}

// ── Raw catalog (group → entries) ───────────────────────────────────────
const RAW: Array<[string, string[]]> = [
  ['Technology', [
    'Artificial Intelligence|artificial intelligence, ai, machine learning, chatgpt',
    'AI Safety & Ethics|ai safety, ai regulation, ai ethics, artificial intelligence risk',
    'Semiconductors|semiconductor, chip industry, nvidia, tsmc, intel',
    'Cybersecurity|cyberattack, data breach, ransomware, hacking, cybersecurity',
    'Smartphones|smartphone, iphone, android, mobile launch',
    'Consumer Gadgets|gadget review, new device launch, wearable tech, smartwatch',
    'Social Media|social media, tiktok, instagram, facebook, x twitter',
    'Cryptocurrency|bitcoin, ethereum, cryptocurrency, crypto market',
    'Web3 & DeFi|defi, web3, blockchain, nft, decentralized finance',
    'Startups|startup funding, venture capital, seed round, unicorn startup',
    'Big Tech|google, apple, microsoft, amazon, meta, big tech',
    'Space Technology|spacex, rocket launch, satellite, reusable rocket',
    'Satellites & Orbit|satellite constellation, starlink, earth observation',
    'Quantum Computing|quantum computing, quantum computer, qubit, quantum supremacy',
    'Robotics|robot, robotics, humanoid robot, industrial automation',
    'Drones|drone, unmanned aerial vehicle, drone delivery, drone strike',
    'Autonomous Vehicles|self driving car, autonomous vehicle, tesla autopilot, waymo',
    'Electric Vehicles|electric vehicle, ev charging, tesla, battery car',
    'Gaming Industry|video game, game release, playstation, xbox, nintendo',
    'Esports|esports, esports tournament, professional gaming, game championship',
    'Streaming Services|netflix, disney+, streaming service, streaming platform',
    'Virtual Reality|virtual reality, vr headset, meta quest, immersive technology',
    'Augmented Reality|augmented reality, ar glasses, mixed reality',
    'Wearables & Fitness Tech|fitness tracker, smart ring, health wearable',
    '3D Printing|3d printing, additive manufacturing, printed organ',
    'Biotech & Genetics|crispr, gene editing, biotech, genetic engineering',
    'Longevity Research|longevity, anti aging, life extension, biological age',
    'Brain-Computer Interfaces|neuralink, brain computer interface, neural implant',
    'Internet Infrastructure|undersea cable, internet backbone, cdn, network outage',
    'Cloud Computing|cloud computing, aws, azure, google cloud, data center',
    'Open Source|open source, linux, github, foss license',
    'Programming & Dev|software developer, programming language, javascript, python',
    'Data & Analytics|big data, data science, analytics platform, data visualization',
    'Privacy Tech|privacy, data protection, gdpr, surveillance, encryption',
    'AR/VR Gaming|vr gaming, ar game, virtual world gaming',
    'Nuclear Fusion Energy|nuclear fusion, fusion reactor, iter, fusion breakthrough',
    'Battery Technology|battery breakthrough, solid state battery, lithium ion',
    'Solar Energy|solar power, photovoltaic, solar farm, panel efficiency',
    'Wind Energy|wind turbine, offshore wind, wind farm',
    'Climate Tech|carbon capture, climate technology, green hydrogen, decarbonization',
    'Smart Cities|smart city, urban technology, city sensors, digital twin city',
    'Fintech|fintech, payment app, digital banking, neobank',
    'Digital Payments|digital wallet, apple pay, contactless payment, mobile payment',
    'E-commerce|ecommerce, online retail, amazon store, shopping platform',
    'Tech Layoffs & Jobs|tech layoff, hiring freeze, tech job cut',
    'Tech Regulation|tech antitrust, digital markets act, platform regulation',
    'Misinformation Online|misinformation, disinformation, fake news, deepfake',
    'Deepfakes|deepfake, synthetic media, voice cloning, ai generated video',
    'Creator Economy|content creator, influencer economy, youtube creator, patreon',
  ]],
  ['Science', [
    'Space Exploration|space mission, nasa, esa, spacewalk, space station',
    'Mars Missions|mars rover, mars mission, perseverance, mars sample',
    'Moon Missions|lunar mission, artemis, moon landing, lunar south pole',
    'James Webb Telescope|james webb telescope, webb observation, deep field, exoplanet discovery',
    'Exoplanets|exoplanet, habitable zone, exoplanet discovery, trappist',
    'Black Holes|black hole, event horizon, gravitational wave, singularity',
    'Astronomy|astronomy, telescope, cosmic discovery, supernova, nebula',
    'Astrophysics|dark matter, dark energy, cosmology, big bang',
    'Solar Physics|solar flare, sunspot, solar storm, aurora, space weather',
    'Asteroids & Comets|asteroid, comet, near earth object, planetary defense',
    'Physics Research|particle physics, cern, higgs boson, neutrino',
    'Chemistry|chemistry breakthrough, new material, chemical compound, polymer',
    'Materials Science|superconductor, metamaterial, graphene, material discovery',
    'Paleontology|dinosaur, fossil discovery, paleontology, prehistoric',
    'Archaeology|archaeology, ancient settlement, excavation, artifact discovery',
    'Human Evolution|human evolution, ancient dna, hominin, fossil ancestor',
    'Genetics Research|genome, dna sequencing, genetic study, epigenetics',
    'Neuroscience|brain research, neuroscience, neural circuit, brain scan',
    'Psychology Research|psychology study, cognitive science, behaviour study',
    'Ocean Science|ocean research, deep sea, hydrothermal vent, ocean current',
    'Marine Biology|marine biology, coral reef, whale study, ocean life',
    'Wildlife Conservation|endangered species, wildlife conservation, poaching, habitat loss',
    'Biodiversity|biodiversity, species discovery, ecosystem study, extinction',
    'Entomology|insect study, bee population, pollinator, ant colony',
    'Ornithology|bird migration, bird population, rare bird, bird song study',
    'Zoology|animal behaviour study, new mammal species, zoology',
    'Botany|plant discovery, forest study, tree research, plant science',
    'Volcanoes|volcano eruption, volcanic ash, lava flow, eruption warning',
    'Earthquakes|earthquake, seismic activity, fault line, aftershock',
    'Extreme Weather|hurricane, typhoon, tornado, heatwave, storm surge',
    'Climate Science|climate study, global warming, climate model, ipcc',
    'Glaciology|glacier melt, ice sheet, sea level rise, permafrost',
    'Antarctic Research|antarctica, ice core, polar research, antarctic expedition',
    'Arctic Research|arctic, sea ice, polar bear, arctic shipping',
    'Water Science|water scarcity, drought, groundwater, water quality',
    'Soil & Agriculture Science|soil health, crop science, agronomy, precision agriculture',
    'Food Science|food technology, lab grown meat, fermentation, food safety',
    'Medicine Research|clinical trial, medical breakthrough, drug discovery',
    'Vaccines|vaccine development, immunisation, mrna vaccine, vaccine rollout',
    'Epidemiology|outbreak, epidemic study, disease surveillance, epidemiology',
    'Aging Science|cellular aging, senescence, age related disease',
    'Sleep Science|sleep study, circadian rhythm, sleep disorder research',
    'Exercise Science|exercise physiology, sports science, fitness study',
    'Nutrition Science|nutrition study, diet research, ultra processed food',
    'Mental Health Research|mental health study, depression research, anxiety study',
    'Reproductive Science|fertility research, ivf, embryo study',
    'Rare Diseases|rare disease, orphan drug, genetic disorder',
    'Cancer Research|cancer study, oncology, immunotherapy, tumour research',
    'Microbiology|microbiology, bacteria study, virus research, antimicrobial',
    'Nuclear Science|nuclear physics, isotope, nuclear research facility',
  ]],
  ['Business & Finance', [
    'Stock Markets|stock market, shares, s&p 500, nasdaq, market close',
    'Central Banks & Rates|federal reserve, bank of england, ecb, interest rate decision',
    'Inflation & Cost of Living|inflation, consumer prices, cost of living, cpi',
    'Corporate Earnings|earnings report, quarterly results, profit guidance',
    'Mergers & Acquisitions|merger, acquisition, takeover bid, buyout',
    'IPOs & Markets|ipo, public offering, stock debut, market listing',
    'Banking|banking, bank profit, lender, retail bank',
    'Housing Market|housing market, house prices, mortgage rates, property listing',
    'Rent & Tenancy|rent prices, tenant rights, rental market, landlord',
    'Commercial Property|commercial real estate, office space, property fund',
    'Oil & Gas|oil price, crude oil, opec, energy company',
    'Mining & Commodities|mining, commodity prices, copper, lithium mining',
    'Gold & Precious Metals|gold price, bullion, precious metal, silver market',
    'Retail & High Street|retail sales, high street, store closing, chain store',
    'Luxury Goods|luxury brand, lvmh, luxury sales, haute couture',
    'Airlines & Aviation Business|airline industry, air travel demand, airline profit',
    'Shipping & Logistics|container shipping, supply chain, port congestion, freight',
    'Rail Industry|rail industry, train operator, rail infrastructure',
    'Auto Industry|car manufacturer, auto sales, vehicle production',
    'Aerospace & Defence|defence contract, arms industry, aerospace company',
    'Insurance|insurance industry, premium rise, underwriting, claims',
    'Pensions & Retirement|pension, retirement saving, pension fund, annuity',
    'Taxes & Fiscal Policy|tax policy, budget, fiscal, tax cut, treasury',
    'Government Spending|public spending, government budget, deficit, spending review',
    'National Debt|national debt, bond yield, gilt, treasury auction',
    'Trade & Tariffs|trade deal, tariff, export control, trade dispute',
    'Labour Market|jobs report, unemployment, hiring, wage growth, strike ballot',
    'Unions & Strikes|trade union, strike action, industrial dispute, walkout',
    'Workplace Trends|remote work, hybrid working, return to office, four day week',
    'Small Business|small business, sole trader, business rates, sme',
    'Franchising & Consumer Brands|franchise brand, consumer staple, brand recall',
    'Advertising Industry|advertising market, ad spend, digital advertising, ad agency',
    'Media Business|media company, newspaper group, publisher, broadcast revenue',
    'Telecoms Business|telecom operator, mobile network, broadband provider, 5g rollout',
    'Energy Utilities|energy company, utility bill, electricity price, grid operator',
    'Water Utilities|water company, water bill, sewage, water regulator',
    'Venture & Startup Funding|funding round, series a, startup raise, venture fund',
    'Private Equity|private equity, buyout fund, leverage, portfolio company',
    'Sovereign Wealth & Funds|sovereign wealth fund, pension giant, fund manager',
    'Economic Indicators|gdp, economic growth, recession risk, economic survey',
    'Emerging Markets|emerging market, developing economy, brics, frontier market',
    'China Economy|china economy, chinese exports, beijing stimulus, yuan',
    'India Economy|india economy, indian gdp, rupee, mumbai market',
    'European Economy|eurozone, eu economy, german industry, french reform',
    'Africa Economy|africa trade, african development, afcfta, african startup',
    'Latin America Economy|latin america economy, brazil inflation, argentina debt',
    'Middle East Economy|gulf economy, saudi vision, opec+ economy, dubai finance',
    'Bankruptcy & Restructuring|bankruptcy, administration, insolvency, creditor',
    'Financial Crime|financial fraud, money laundering, sanctions evasion, sec charge',
    'Fraud & Scams|scam, fraud alert, phishing, investment scam',
  ]],
  ['Politics & World', [
    'UK Politics|westminster, prime minister, house of commons, labour, tory',
    'US Politics|congress, white house, senate, republican, democrat',
    'EU Politics|european union, european commission, eu council, eu parliament',
    'Elections|election, ballot, polling day, exit poll, vote count',
    'Polling & Opinion|opinion poll, approval rating, survey, swing voter',
    'Polling & Campaigns|campaign trail, campaign ad, canvassing, get out the vote',
    'Populism|populist party, far right, far left, anti establishment',
    'Protests & Movements|protest, demonstration, mass rally, civil disobedience',
    'Diplomacy|diplomatic talks, summit meeting, bilateral, ambassador',
    'Sanctions|sanctions, economic sanctions, sanctions package, asset freeze',
    'NATO|nato, alliance summit, article 5, nato expansion',
    'United Nations|united nations, security council, general assembly, un resolution',
    'Middle East Conflict|middle east conflict, ceasefire talks, gaza, israel',
    'Ukraine War|ukraine war, frontline ukraine, kyiv, russian offensive',
    'Russia Politics|kremlin, putin, duma, russian opposition',
    'China Politics|chinese communist party, beijing leadership, xi jinping, politburo',
    'Taiwan Strait|taiwan strait, taiwan defence, cross strait, taiwan election',
    'Korean Peninsula|north korea, kim jong un, inter korean, missile test',
    'Indo-Pacific|indo pacific, quad, asean summit, pacific islands',
    'South Asia Politics|india politics, lok sabha, delhi government, pakistani politics',
    'Africa Politics|african union, coup, african election, sahel',
    'Latin America Politics|latin america politics, brazil politics, venezuela crisis, mexico election',
    'Migration & Borders|migration, border crossing, asylum claim, refugee camp',
    'Human Rights|human rights, amnesty report, political prisoner, rights watchdog',
    'Press Freedom|press freedom, journalist detained, media crackdown, reporter safety',
    'Corruption|corruption scandal, bribery case, anti corruption probe, embezzlement',
    'Spying & Intelligence|intelligence agency, spy case, espionage charge, surveillance programme',
    'Cyber Warfare|state hacking, cyber espionage, cyber army, critical infrastructure attack',
    'Terrorism|terrorism, extremist attack, counter terror, radicalisation',
    'Defence & Military|defence spending, military exercise, troops deployment, army reform',
    'Nuclear Policy|nuclear weapon, non proliferation, arms control, warhead',
    'Space Policy|space policy, space law, orbital regulation, artemis accord',
    'Climate Policy|cop summit, climate pledge, emissions target, carbon budget',
    'Energy Policy|energy security, north sea oil, nationalisation, grid reform',
    'Health Policy|health service, nhs, healthcare reform, medical funding',
    'Education Policy|school funding, curriculum reform, university policy, tuition',
    'Policing & Crime|police, crime statistics, policing reform, knife crime',
    'Justice & Courts|supreme court, high court ruling, judiciary, verdict',
    'Prisons & Rehabilitation|prison service, inmate, parole, rehabilitation programme',
    'Local Government|council tax, local council, mayoral, devolution deal',
    'Scottish Politics|scottish government, holyrood, snp, scottish independence',
    'Welsh Politics|welsh government, senedd, welsh labour',
    'Northern Ireland Politics|stormont, dup, sinn fein, northern ireland executive',
    'Monarchy|royal family, king charles, royal tour, royal household',
    'US States & Cities|governor, state legislature, city hall, municipal politics',
    'Canada Politics|canadian parliament, ottawa, trudeau, canadian election',
    'Australia & NZ Politics|australian politics, canberra, wellington, aussie election',
    'Southeast Asia Politics|asean politics, myanmar junta, thai election, indonesia politics',
    'Caucasus & Central Asia|caucasus, armenia azerbaijan, kazakhstan, central asia summit',
    'Balkans Politics|balkans, serbia kosovo, bosnia, western balkans summit',
  ]],
  ['Health', [
    'Public Health|public health, health agency, outbreak response, health advisory',
    'NHS & Health Services|nhs, hospital waiting list, gp appointment, ambulance delay',
    'Hospitals|hospital, a&e waiting, hospital trust, ward closure',
    'Mental Health|mental health, therapy access, crisis support, psychiatrist',
    'Depression & Anxiety|depression, anxiety disorder, antidepressant, mood study',
    'Long Covid|long covid, post covid condition, fatigue syndrome',
    'Cancer Care|cancer treatment, chemotherapy, oncology ward, cancer screening',
    'Heart Health|heart disease, cardiology, blood pressure, cholesterol',
    'Diabetes|diabetes, insulin, glucose monitor, type 2 diabetes',
    'Obesity & Weight|obesity, weight loss drug, bmi, ozempic',
    'Weight Loss Drugs|weight loss injection, glp-1, semaglutide, obesity drug trial',
    'Nutrition & Diet|diet, nutrition guidance, food label, healthy eating',
    'Ultra-Processed Foods|ultra processed food, additive, processed meat study',
    'Alcohol & Health|alcohol guidance, drinking limit, liver health, sober curious',
    'Smoking & Vaping|vaping, e cigarette, nicotine, smoking ban',
    'Drug Policy|drug policy, decriminalisation, cannabis legalisation, harm reduction',
    'Reproductive Health|abortion law, contraception, reproductive rights, birth control',
    'Childbirth & Maternity|maternity care, midwife, birth rate, maternity ward',
    'Children Health|child health, vaccination schedule, paediatric, childhood obesity',
    "Men's Health|prostate, testicular cancer, men health screening, testosterone",
    "Women's Health|menopause, endometriosis, breast screening, women health research",
    'Ageing & Elderly Care|care home, dementia care, elderly support, social care',
    'Dementia & Alzheimer|dementia, alzheimer, memory clinic, cognitive decline',
    'Rare Disease Research|rare disease day, orphan disease, patient trial',
    'Organ Donation|organ donor, transplant list, kidney transplant, donor register',
    'Blood & Donation|blood donation, blood shortage, donor session, plasma',
    'Dental Health|dentist, dental care, oral health, nhs dentistry',
    'Eye Health|eye health, vision loss, cataract surgery, optician',
    'Hearing Health|hearing loss, hearing aid, audiology, tinnitus',
    'Allergies|allergy, anaphylaxis, food allergy, pollen count',
    'Autoimmune Conditions|autoimmune, lupus, ms treatment, immune disorder',
    'Gut Health|gut microbiome, probiotic, digestive health, ibs',
    'Skin & Dermatology|skin condition, dermatology, eczema, psoriasis',
    'Pain Management|chronic pain, painkiller guidance, physiotherapy, opioid',
    'Emergency Medicine|paramedic, emergency response, trauma care, air ambulance',
    'Medical Devices|medical device, implant recall, regulator warning, device trial',
    'AI in Medicine|ai diagnosis, medical ai, algorithm health, radiology ai',
    'Gene Therapy|gene therapy, clinical gene trial, inherited disease treatment',
    'Health Insurance|health insurance, premium, coverage dispute, private health',
    'Medical Ethics|medical ethics, consent case, clinical trial ethics, end of life care',
    'Alternative Medicine|supplement, alternative therapy, acupuncture study, herbal',
    'Sleep Health|insomnia, sleep hygiene, sleep clinic, sleep tracking',
    'Fitness Trends|fitness trend, gym membership, home workout, fitness app',
    'Running & Endurance|marathon training, endurance sport, race result, runner study',
    'Disability Rights|disability rights, accessibility, disability benefit, adaptive sport',
    'Antibiotics Resistance|antimicrobial resistance, superbug, antibiotic stewardship',
    'Global Health|global health, who, pandemic treaty, health aid',
    'Water Contamination|water contamination, lead pipes, pfas, drinking water safety',
    'Air Quality & Health|air quality, pollution health, pm2.5, asthma rates',
    'Noise Pollution|noise pollution, traffic noise, hearing study, quiet zone',
  ]],
  ['Sports', [
    'Football|football, premier league, transfer news, football match',
    'Premier League|premier league, epl table, premier league matchday',
    'Champions League|champions league, ucl draw, european cup night',
    'International Football|world cup qualifier, international friendly, nations league',
    'World Cup|world cup, fifa, world cup draw, host nation',
    'Transfer Window|transfer window, transfer fee, medical completed, deal agreed',
    'La Liga & Serie A|la liga, serie a, el clasico, milan derby',
    'Bundesliga & Ligue 1|bundesliga, ligue 1, bayern munich, psg',
    'MLS & US Soccer|mls, major league soccer, us soccer, mls playoffs',
    'Women\u2019s Football|women\u2019s football, wsl, lionesses, women\u2019s super league',
    'Cricket|cricket, test match, t20, odi series',
    'Tennis|tennis, grand slam, atp, wta, tennis ranking',
    'Wimbledon|wimbledon, all england club, grass court, wimbledon final',
    'Formula 1|formula 1, f1 grand prix, f1 qualifying, constructor standings',
    'Motorsport|motorsport, rally, endurance racing, motogp',
    'Golf|golf, pga tour, major championship, ryder cup',
    'Rugby Union|rugby union, six nations, rugby world cup, test match rugby',
    'Rugby League|rugby league, super league, challenge cup, state of origin',
    'Boxing|boxing, title fight, undercard, boxing champion',
    'UFC & MMA|ufc, mma fight card, ufc champion, octagon',
    'Athletics|athletics, world championships, track and field, marathon record',
    'Olympics|olympics, olympic games, olympic qualification, team gb',
    'Paralympics|paralympics, paralympic games, para athlete, classification',
    'Winter Sports|winter sports, skiing world cup, snowboard, figure skating',
    'Cycling|cycling, tour de france, giro, uci worldtour',
    'Swimming|swimming, world aquatics, swimming record, pool final',
    'Basketball|basketball, nba, nba playoffs, euroleague',
    'American Football|nfl, super bowl, nfl draft, touchdown',
    'Baseball|baseball, mlb, world series, pitching',
    'Ice Hockey|nhl, ice hockey, stanley cup, hockey playoff',
    'Horse Racing|horse racing, grand national, derby, racecourse',
    'Sailing & Yachting|sailing, america\u2019s cup, volvo ocean race, regatta',
    'Rowing|rowing, boat race, henley, rowing world cup',
    'Snooker & Pool|snooker, world snooker championship, crucible, break',
    'Darts|darts, pdc, world darts championship, nine darter',
    'Chess|chess, chess championship, grandmaster, chess world cup',
    'Esports & Gaming Sports|esports, league of legends worlds, dota major, fps major',
    'Table Sports|table tennis, ping pong championship, squash tour',
    'Combat Sports News|judo, taekwondo, wrestling championship, karate',
    'Triathlon & Multisport|triathlon, ironman, duathlon, transition split',
    'Climbing|sport climbing, bouldering, ifsc, climbing world cup',
    'Surfing|surfing, world surf league, big wave, surf contest',
    'Skiing|alpine skiing, downhill world cup, slalom, ski jumping',
    'Ski Jumping|ski jumping, four hills, vikersund, jumping hill record',
    'Speed Skating|speed skating, long track, short track, world record',
    'Skateboarding|skateboarding, street league, olympic skateboarding, x games',
    'Handball|handball, ehf champions league, handball world championship',
    'Volleyball|volleyball, volleyball nations league, beach volleyball',
    'Water Polo|water polo, world aquatics championship, water polo league',
    'Gymnastics|gymnastics, world gymnastics championships, all around, apparatus final',
    'Youth & Grassroots Sport|grassroots sport, youth academy, local league, school sport',
  ]],
  ['Culture & Media', [
    'Movies|film, movie release, box office, film review, premiere',
    'Movie Awards|oscars, academy awards, bafta, award season',
    'TV & Streaming Shows|tv series, season finale, streaming hit, renewed series',
    'Music|music release, album drop, single, chart position',
    'Music Awards & Charts|grammys, billboard, uk charts, number one single',
    'Concerts & Tours|concert, tour dates, festival lineup, live show',
    'Festivals|glastonbury, coachella, festival season, literary festival',
    'Pop Culture|celebrity, viral moment, pop culture, red carpet',
    'Celebrity News|celebrity split, celebrity wedding, star announcement',
    'Theatre & Stage|theatre, west end, broadway, stage play, curtain call',
    'Opera & Classical|opera, philharmonic, classical concert, maestro',
    'Dance & Ballet|ballet, contemporary dance, royal ballet, choreographer',
    'Visual Arts|art exhibition, gallery, museum show, art fair',
    'Art Market|art auction, record sale, christie\u2019s, sotheby\u2019s',
    'Photography|photography, photo series, world press photo, camera launch',
    'Architecture|architecture, building design, starchitect, planning approval',
    'Design|design week, product design, brand redesign, design award',
    'Fashion|fashion week, runway, collection, fashion house',
    'Fashion Business|luxury group, fashion profit, supply chain fashion',
    'Beauty Industry|beauty brand, skincare launch, cosmetics regulation',
    'Books & Publishing|book release, novel, publishing deal, bestseller',
    'Literary Awards|booker prize, literary award, shortlist, winner announced',
    'Poetry & Spoken Word|poetry, poetry collection, spoken word, poet laureate',
    'Comedy|comedy, stand up, comedy special, comedian tour',
    'Podcasts|podcast, podcast chart, new podcast series',
    'Radio|radio, broadcast rating, radio show, presenter',
    'Animation|animation, animated film, studio ghibli, pixar',
    'Anime & Manga|anime, manga, shonen jump, anime season',
    'Comic Books|comic book, marvel, dc comics, graphic novel',
    'Board Games & Tabletop|board game, tabletop, dungeons and dragons, boardgame release',
    'Museums & Exhibitions|museum, exhibition opening, gallery blockbustr, artefact return',
    'Heritage & Restoration|heritage site, restoration project, listed building, monument',
    'Libraries|library, library service, reading programme, book ban',
    'Awards Season|awards ceremony, red carpet, nominees, statuette',
    'Fan Culture & Fandom|fandom, fan convention, cosplay, fan community',
    'Science Fiction & Fantasy|sci fi, fantasy series, new novel, worldbuilding',
    'True Crime|true crime, documentary series, cold case, courtroom drama',
    'Documentaries|documentary, doc premiere, film festival, nonfiction',
    'Film Festivals|cannes, venice film festival, sundance, berlinale, toronto',
    'Independent Film|indie film, limited release, indie director, sundance hit',
    'Video Game Culture|gaming community, game awards, speedrun, game mod',
    'Internet Culture|meme, viral trend, online community, challenge',
    'Language & Words|new word, dictionary update, etymology, language study',
    'History Features|history, anniversary, historical discovery, archive find',
    'Royal & Aristocracy|royal household, duke, duchess, palace statement',
    'Religion News|religion, church of england, vatican, interfaith',
    'Philosophy & Ideas|philosophy, ethics debate, public intellectual, lecture',
    'Death & Obituaries|obituary, died aged, tribute, funeral',
    'Quirky News|odd news, world record attempt, unusual event, strange discovery',
    'Food & Drink Culture|restaurant review, new opening, chef, tasting menu',
    'Coffee & Tea Culture|coffee, barista, tea ceremony, cafe culture',
    'Wine & Spirits|wine, whisky, vintage, sommelier, distillery',
    'Beer & Brewing|craft beer, brewery, ale festival, lager launch',
  ]],
  ['Lifestyle & Interests', [
    'Travel Guides|travel guide, itinerary, city break, where to stay',
    'Air Travel Tips|flight tip, airline review, airport guide, lounge review',
    'Rail Travel|rail journey, train route, scenic railway, Interrail',
    'Road Trips|road trip, driving route, campervan, highway journey',
    'Cruises|cruise, cruise ship, itinerary port, cruise review',
    'Hotels & Resorts|hotel review, resort opening, boutique hotel, hotel star',
    'Adventure Travel|adventure travel, expedition, trek, wild camping',
    'National Parks|national park, trail guide, park ranger, park opening',
    'Hiking & Walking|hiking, walking route, long distance trail, munro',
    'Camping|camping, campsite, tent review, wild camping rules',
    'Cycling Holidays|cycling holiday, bike tour, eurovelo, saddle',
    'Sustainable Travel|sustainable travel, slow travel, green tourism, carbon flight',
    'Destination Food|street food, local dish, food tour, regional cuisine',
    'Cities & City Life|city living, urban design, pedestrian street, megacity',
    'Islands|island getaway, island guide, ferry route, remote island',
    'Mountains|mountain guide, alpine hut, summit, mountain rescue',
    'Deserts & Safari|desert trek, safari lodge, wildlife drive, national reserve',
    'Polar Travel|polar expedition, antarctic cruise, arctic voyage, ice camp',
    'Gardening|gardening, garden design, allotment, planting season',
    'Plants & Houseplants|houseplant, plant care, monstera, propagation',
    'Home Improvement|home improvement, renovation, extension, builder',
    'Interior Design|interior design, home decor, room makeover, furniture',
    'Minimalism & Decluttering|minimalism, declutter, tidy home, capsule wardrobe',
    'DIY & Makers|diy project, maker, workshop, power tool',
    'Recipes & Cooking|recipe, home cooking, baking, how to cook',
    'Baking|baking, sourdough, pastry, cake recipe, bake off',
    'Vegan & Plant-Based|vegan, plant based, vegan recipe, vegan product launch',
    'Vegetarian Cooking|vegetarian recipe, meat free, veggie launch',
    'Budget Cooking|budget meal, cheap recipe, batch cooking, storecupboard',
    'Parenting|parenting, child development, school run, mum advice',
    'Pregnancy & New Parents|pregnancy, newborn, baby advice, antenatal',
    'Family Activities|family day out, kids activity, half term, rainy day',
    'Relationships|relationship, dating trend, couple study, marriage',
    'Weddings|wedding, bridal, wedding dress, hen do, stag do',
    'Dating Apps|dating app, match study, online dating, hinge, bumble',
    'Personal Finance Tips|money tip, saving rate, budgeting, debt free',
    'Investing Basics|investing basics, index fund, isa, portfolio',
    'Retirement Planning|retirement planning, pension pot, drawdown, later life',
    'Frugal Living|frugal, money saving, no spend, thrifty',
    'Side Hustles|side hustle, freelance income, extra income, gig work',
    'Careers & Interviewing|job interview, cv tip, career change, hiring process',
    'Remote Work Life|remote work, digital nomad, workation, home office setup',
    'Productivity|productivity, time management, focus study, habit',
    'Study & Exams|exam, revision, study tip, results day',
    'Universities|university, admissions, campus life, clearing',
    'Student Life|student finance, halls, freshers, student union',
    'Language Learning|language learning, duolingo, immersion, fluency',
    'Pets & Animals|pet, dog training, cat behaviour, vet advice',
    'Dogs|dog breed, dog walk, puppy training, dog rescue',
    'Cats|cat behaviour, kitten, cat breed, cattery',
    'Birdwatching|birdwatching, twitching, rare sighting, rspb reserve',
    'Astrology & Horoscopes|horoscope, zodiac, star sign, astrology',
    'Lottery & Prizes|lottery, jackpot, winning ticket, prize draw',
    'Volunteering & Charity|volunteer, charity campaign, fundraising, good cause',
    'Faith & Spirituality|spirituality, mindfulness practice, retreat, meditation',
    'Wellness Trends|wellness, spa, cold plunge, sauna study',
  ]],
  ['Environment', [
    'Climate Change|climate change, global warming, temperature record, climate impact',
    'Net Zero Targets|net zero, carbon neutral, emissions cut, net zero pledge',
    'Carbon Markets|carbon credit, carbon offset, ets, cap and trade',
    'Rewilding|rewilding, species reintroduction, beaver release, wild land',
    'Reforestation|tree planting, forest restoration, afforestation, seed collection',
    'Plastic Pollution|plastic pollution, ocean plastic, single use plastic, microplastic',
    'Recycling & Waste|recycling, waste collection, landfill, deposit return',
    'Fast Fashion Waste|fast fashion, textile waste, clothing landfill, resale',
    'Renewable Energy Transition|renewable energy, clean power, grid transition, green electricity',
    'Hydrogen Economy|hydrogen economy, green hydrogen, hydrogen train, electrolyser',
    'Nuclear Energy Debate|nuclear power, new reactor, smr, nuclear waste',
    'Coal Phase-Out|coal plant closure, coal phase out, coal mine',
    'Grid & Storage|grid upgrade, battery storage gwh, interconnector, substation',
    'Heat Pumps & Home Energy|heat pump, home insulation, energy efficiency, retrofit',
    'EV Charging Network|ev charging point, charging network, rapid charger, charging row',
    'Aviation Emissions|flight emissions, sustainable aviation fuel, plane co2',
    'Shipping Emissions|shipping emissions, maritime fuel, port electrification',
    'Farming & Climate|sustainable farming, regenerative agriculture, farm emissions',
    'Meat & Dairy Impact|meat emission, dairy footprint, protein shift',
    'Water Scarcity|water scarcity, reservoir level, hosepipe ban, drought order',
    'Flooding|flood warning, flood defence, river burst, flood insurance',
    'Wildfires|wildfire, bushfire, fire season, containment',
    'Ocean Acidification|ocean acidification, coral bleaching, reef survey, ph study',
    'Great Barrier Reef|great barrier reef, reef bleaching, crown of thorns, reef restoration',
    'Amazon Rainforest|amazon, deforestation, rainforest protection, amazon reserve',
    'Arctic Melt|arctic ice melt, sea ice minimum, polar amplification',
    'Antarctic Ice Sheet|antarctic ice sheet, thwaites, ice shelf collapse',
    'Glacier Retreat|glacier retreat, glacier survey, snowline, glacier lake',
    'Permafrost Thaw|permafrost, methane release, ground thaw, yedoma',
    'Species on the Brink|critically endangered, iucn red list, last of species, captive breeding',
    'Tiger Conservation|tiger population, tiger reserve, poaching arrest, corridor',
    'Elephant Protection|elephant population, ivory seizure, elephant corridor, human elephant conflict',
    'Pangolins & Illegal Trade|pangolin, illegal wildlife trade, seizure, trafficking route',
    'Shark Conservation|shark, finning ban, shark sanctuary, bycatch',
    'Whaling & Whale Protection|whaling, whale sanctuary, whale strandings, humpback recovery',
    'Bee Decline|bee decline, pollinator crisis, neonicotinoid, wild bee survey',
    'Insect Collapse|insect decline, biomass study, bug survey, pesticide',
    'Bird Migration Changes|bird migration shift, breeding season, flyway, radar study',
    'Invasive Species|invasive species, hitchhiker pest, biosecurity, eradication',
    'Light Pollution|light pollution, dark sky reserve, nocturnal wildlife, skyglow',
    'Chemical Pollution|pfas, forever chemicals, pesticide residue, effluent',
    'Mining Impact|mining pollution, tailings dam, river contamination, mine protest',
    'Deep-Sea Mining|deep sea mining, seabed lease, moratorium, nodule',
    'Green Cities|green city, urban tree canopy, park expansion, air quality plan',
    'Circular Economy|circular economy, repairability, product lifespan, ecodesign',
    'Greenwashing|greenwashing, advertising claim, regulator ruling, green claim',
    'Environmental Law|environmental law, court ruling climate, judgment, eco lawsuit',
    'Climate Activism|climate protest, just stop oil, extinction rebellion, school strike',
    'Climate Adaptation|adaptation plan, sea wall, heat plan, resilience fund',
    'Conservation Funding|conservation funding, biodiversity finance, debt for nature',
  ]],
  ['Education & Society', [
    'Schools & Teaching|school, teacher, classroom, ofsted, lesson',
    'Exams & Assessment|gcse, a level, exam board, grade boundary',
    'University Research|research paper, peer reviewed, study finding, university study',
    'Academic Freedom|academic freedom, campus protest, professor dismissed, tenure',
    'Student Protests|campus encampment, student union, tuition protest',
    'EdTech|edtech, learning app, classroom technology, online course',
    'AI in Education|ai homework, chatgpt school, ai marking, classroom ai policy',
    'Adult Learning|evening class, retraining, adult course, upskilling',
    'Museums & Learning|museum education, school visit, outreach programme',
    'Libraries & Access|library funding, digital lending, book access',
    'Social Mobility|social mobility, disadvantaged pupil, attainment gap',
    'Child Welfare|child protection, social worker, safeguarding review',
    'Youth Trends|gen z, gen alpha, youth survey, teenage trend',
    'Generational Shifts|millennial, boomer, generation study, cohort',
    'Gender Equality|gender pay gap, women in leadership, gender study',
    'LGBTQ+ News|lgbtq, pride, trans policy, queer community',
    'Race & Ethnicity|race equality, ethnic minority study, discrimination case',
    'Disability Inclusion|disability inclusion, workplace adjustment, accessible design',
    'Housing & Homelessness|homelessness, rough sleeping, shelter, hostel, outreach team',
    'Poverty & Welfare|food bank, universal credit, child poverty, benefits',
    'Food Banks|food bank use, parcel record, referral, donation drive',
    'Charity Sector|charity commission, nonprofit funding, volunteer surge',
    'Volunteering|volunteer scheme, community project, big help out',
    'Faith Communities|mosque, church hall, synagogue, gurdwara, community faith',
    'Rural Life|rural community, village pub, farm village, countryside',
    'Urbanism & Transport|urban planning, bus route, cycle lane, low traffic neighbourhood',
    'Public Transport|bus service, rail fare, transport funding, metro extension',
    'Driver News|fuel duty, parking charge, driving test, road scheme',
    'Road Safety|road death, speed limit, casualty figures, vision zero',
    'Water Shortages|hosepipe, water saving, leak figures, supply plan',
    'Bins & Council Services|bin collection, council service cut, tip charge, fly tipping',
    'Consumer Rights|consumer rights, refund rule, which? warning, trading standards',
    'Product Recalls|product recall, safety notice, recalled model, trading alert',
    'Scam Alerts|scam warning, fraud surge, cold call, bank transfer scam',
    'Retirement Communities|retirement village, later living, downsizing, over 60s housing',
    'Care Sector|care worker, care home inspection, domiciliary care, vacancy',
    'Adoption & Fostering|adoption, foster carer, looked after child, matching',
    'Migrants & Integration|integration policy, language class, resettlement, community sponsorship',
    'Religion & Society|religious study, church attendance, secularisation survey',
    'Voluntary Sector News|community interest company, social enterprise, mutual aid',
    'Fire Service|fire service, station closure, firefighter strike, response time',
    'Ambulance Service|ambulance response, paramedic vacancy, handover delay',
    'Coastguard & Sea Safety|coastguard, lifeboat launch, sea safety, RNLI',
    'Mountain Rescue|mountain rescue, callout, fell rescue, lost hiker',
    'Lifeboat & Water Safety|lifeboat crew, rip current, water safety campaign, inland water',
  ]],
  ['Regions', [
    'UK News|uk news, britain, london, united kingdom',
    'London|london, greater london, TfL, london mayor',
    'Scotland|scotland, edinburgh, glasgow, scottish',
    'Wales|wales, cardiff, welsh government, eisteddfod',
    'Northern Ireland|northern ireland, belfast, stormont, derry',
    'Ireland|ireland, dublin, dail, taoiseach',
    'US News|us news, washington, american, usa',
    'New York|new york, nyc, manhattan, brooklyn',
    'California|california, los angeles, san francisco, sacramento',
    'Washington DC|washington dc, capitol hill, white house, dc politics',
    'Canada|canada, ottawa, toronto, canadian',
    'Mexico & Central America|mexico, central america, mexico city, guatemala',
    'Brazil & South America|brazil, argentina, colombia, south america',
    'France|france, paris, macron, french',
    'Germany|germany, berlin, german government, bundestag',
    'Spain|spain, madrid, barcelona, spanish',
    'Italy|italy, rome, milan, italian',
    'Netherlands & Belgium|netherlands, belgium, amsterdam, brussels, dutch',
    'Nordic Countries|sweden, norway, denmark, finland, iceland, nordic',
    'Baltic States|estonia, latvia, lithuania, baltic',
    'Poland & Central Europe|poland, hungary, czech, slovakia, visegrad',
    'Balkans|balkans, serbia, croatia, bosnia, kosovo',
    'Greece & Cyprus|greece, cyprus, athens, aegean, nicosia',
    'Turkey|turkey, ankara, istanbul, turkish, turkiye',
    'Russia & Eastern Europe|russia, ukraine, moldova, belarus, eastern europe',
    'Ukraine|ukraine, kyiv, lviv, odesa, ukrainian',
    'Israel & Palestine|israel, palestine, gaza, west bank, jerusalem',
    'Gulf States|saudi arabia, uae, qatar, dubai, riyadh, gulf',
    'Iran|iran, tehran, iranian, irgc',
    'Iraq & Levant|iraq, lebanon, syria, jordan, beirut, baghdad',
    'Egypt & North Africa|egypt, libya, tunisia, morocco, algeria, cairo',
    'Sub-Saharan Africa|nigeria, kenya, south africa, ghana, ethiopia, african union',
    'Sahel & West Africa|sahel, mali, burkina faso, niger, west africa',
    'East Africa|kenya, tanzania, ethiopia, somalia, uganda, east africa',
    'Southern Africa|south africa, zimbabwe, zambia, mozambique, botswana',
    'India & South Asia|india, pakistan, bangladesh, sri lanka, delhi, islamabad',
    'China & Hong Kong|china, hong kong, beijing, shanghai, prc',
    'Taiwan|taiwan, taipei, taiwan strait, roc',
    'Japan|japan, tokyo, japanese, diet',
    'Koreas|south korea, north korea, seoul, pyongyang',
    'Southeast Asia|southeast asia, indonesia, vietnam, thailand, philippines, malaysia',
    'Singapore & Malaysia|singapore, malaysia, kuala lumpur, changi',
    'Philippines|philippines, manila, duterte, pinoy',
    'Australia|australia, sydney, canberra, melbourne, australian',
    'New Zealand & Pacific|new zealand, pacific islands, fiji, wellington, png',
    'Pacific Islands|pacific islands, fiji, samoa, tonga, vanuatu, climate pacific',
    'Central Asia|kazakhstan, uzbekistan, kyrgyzstan, tajikistan, central asia',
    'Caucasus|georgia, armenia, azerbaijan, caucasus',
    'Arctic Region|arctic council, svalbard, nunavut, arctic shipping route',
    'Antarctica|antarctica, antarctic treaty, research station, ice sheet',
    'Caribbean|caribbean, jamaica, cuba, haiti, trinidad',
  ]],
]

// ── Parse once ──────────────────────────────────────────────────────────
function slugify(label: string): string {
  return label
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export const SUBTOPIC_CATALOG: CatalogTopic[] = RAW.flatMap(([group, entries]) =>
  entries.map((raw) => {
    const [label, kw] = raw.split('|')
    return {
      id: slugify(label),
      label,
      keywords: (kw || label).split(',').map((k) => k.trim()).filter(Boolean),
      group,
    }
  }),
)

export const CATALOG_BY_ID: Record<string, CatalogTopic> = Object.fromEntries(
  SUBTOPIC_CATALOG.map((t) => [t.id, t]),
)

export const CATALOG_GROUPS: string[] = RAW.map(([group]) => group)

export const CATALOG_SIZE = SUBTOPIC_CATALOG.length

/** Runtime catalog entries added by the AI factory (RTDB customSubtopics). */
export interface RuntimeTopic {
  id: string
  label: string
  keywords: string[]
  group?: string
  createdBy?: string
  createdAt?: number
}

/** Search the static catalog (label + keyword match, case-insensitive). */
export function searchCatalog(q: string, limit = 60): CatalogTopic[] {
  const query = q.trim().toLowerCase()
  if (!query) return []
  const terms = query.split(/\s+/).filter(Boolean)
  return SUBTOPIC_CATALOG.filter((t) => {
    const hay = `${t.label} ${t.keywords.join(' ')}`.toLowerCase()
    return terms.every((term) => hay.includes(term))
  }).slice(0, limit)
}
