import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { ErrorBoundary } from "@/components/error-boundary";
import { SecretScreenRecorder } from "@/components/secret-screen-recorder";
import { GatedAnalytics } from "@/components/analytics-gated";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // metadataBase: ensures all relative URLs in metadata (OG images, icons,
  // canonical) resolve to absolute URLs using the production domain.
  // Required for correct OG link previews on WhatsApp/Twitter/etc when
  // shared from neutralwire.org.
  metadataBase: new URL("https://neutralwire.org"),
  title: "NeutralWire — See How Every Outlet Spins the Same Story",
  description:
    "Is your news feeding you the full picture? NeutralWire compares how left, right, and center outlets cover the SAME story — side by side. See the bias, spot the spin, decide for yourself. Free, no paywalls, auto-detects your country. Try it before your next headline.",
  keywords: ["news", "bias", "media bias", "neutralwire", "news aggregator", "left right center", "unbiased news", "compare news"],
  authors: [{ name: "NeutralWire" }],
  manifest: "/manifest.json",
  // Google Search Console verification (updated for neutralwire.org domain)
  verification: {
    google: "szdK3fkYGRu3DqBfWpi6i3JpPLhqFZUx8I22qqGSQJA",
  },
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/favicon-32.png",
  },
  appleWebApp: {
    capable: true,
    // "black" (not "default") — the status bar must be dark to match the
    // dark OS launch screen (manifest background_color #0a0a0a + the
    // apple-touch-startup-image set). "default" would flash a white bar
    // over the dark launch. Content still starts BELOW the bar (no
    // overlap, unlike black-translucent), so the layout is unaffected.
    statusBarStyle: "black",
    title: "NeutralWire",
  },
  openGraph: {
    title: "NeutralWire — See How Every Outlet Spins the Same Story",
    description: "Is your news feeding you the full picture? Compare how left, right, and center outlets cover the SAME story — side by side. See the bias, spot the spin, decide for yourself.",
    type: "website",
    siteName: "NeutralWire",
  },
  // Canonical URL: tells search engines that neutralwire.org is the
  // primary domain (not neutralwire.vercel.app). Combined with metadataBase,
  // this produces <link rel="canonical" href="https://neutralwire.org/">.
  alternates: {
    canonical: "/",
  },
  twitter: {
    card: "summary_large_image",
    title: "NeutralWire — See How Every Outlet Spins the Same Story",
    description: "Is your news feeding you the full picture? Compare how left, right, and center outlets cover the SAME story — side by side. See the bias, spot the spin.",
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: true,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="apple-mobile-web-app-title" content="NeutralWire" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        {/* ── iOS PWA launch screens (apple-touch-startup-image) ──
            iOS ignores the manifest's background_color for the home-screen
            launch screen — without these it shows a plain WHITE screen for a
            beat before the first paint, right before our dark splash. Each
            link matches a device via its media query; the PNGs are static
            frames of the animated splash (dark bg + corner glows + wordmark
            + tri-color bar + tagline) at physical pixel sizes, generated by
            scripts/generate-startup-images.js. iOS launch becomes:
            static frame → animated splash (same design) → app. */}
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-640x1136.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-750x1334.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1125x2436.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1170x2532.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1179x2556.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1206x2622.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1242x2208.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-828x1792.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1242x2688.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1284x2778.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1290x2796.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1320x2868.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1536x2048.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1620x2160.png" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1640x2360.png" media="(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1668x2224.png" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1668x2388.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1488x2266.png" media="(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2048x2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2048x2732.png" media="(device-width: 1366px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-1536x2048.png" media="(device-width: 1024px) and (device-height: 768px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2160x1620.png" media="(device-width: 1080px) and (device-height: 810px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2360x1640.png" media="(device-width: 1180px) and (device-height: 820px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2224x1668.png" media="(device-width: 1112px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2388x1668.png" media="(device-width: 1194px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        <link rel="apple-touch-startup-image" href="/apple-launch/startup-2266x1488.png" media="(device-width: 1133px) and (device-height: 744px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" />
        {/* Google Search Console verification — also set via metadata.verification
            above, but duplicated here as a direct meta tag to guarantee it's
            always present in the HTML (Next.js metadata API merging can
            sometimes not include verification when generateMetadata in
            page.tsx returns its own metadata object). */}
        <meta name="google-site-verification" content="szdK3fkYGRu3DqBfWpi6i3JpPLhqFZUx8I22qqGSQJA" />
        {/* iOS PWA: allow standalone display + push notifications */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        {/* ── Performance: preconnect to key external domains ── */}
        {/* Firebase RTDB — used for news cache, summaries, device data.
            preconnect warms the TLS connection so the first Firebase read
            is ~200ms faster (no DNS + TCP + TLS handshake delay). */}
        <link rel="preconnect" href="https://neutralwire-aaedf-default-rtdb.europe-west1.firebasedatabase.app" />
        <link rel="dns-prefetch" href="https://neutralwire-aaedf-default-rtdb.europe-west1.firebasedatabase.app" />
        {/* ipwho.is — client-side country detection fires on EVERY page load;
            preconnecting removes DNS+TLS from its critical path. */}
        <link rel="preconnect" href="https://ipwho.is" />
        <link rel="dns-prefetch" href="https://ipwho.is" />
        {/* Major image CDNs — preconnect so image proxy fetches are faster */}
        <link rel="dns-prefetch" href="https://ichef.bbci.co.uk" />
        <link rel="dns-prefetch" href="https://static01.nyt.com" />
        <link rel="dns-prefetch" href="https://i.guim.co.uk" />
        <link rel="dns-prefetch" href="https://s.france24.com" />
        <link rel="dns-prefetch" href="https://static.independent.co.uk" />
        <link rel="dns-prefetch" href="https://www.japantimes.co.jp" />
        {/* ── Preload the news API — the FIRST request the page makes ──
            Starts the fetch before the JS bundle finishes parsing. With
            SWR caching in the SW, this means the cached response is served
            INSTANTLY on repeat visits, and the fresh fetch starts in
            parallel. fetchpriority="high" tells the browser this is the
            most important resource to fetch.
            NOTE: the param ORDER exactly matches the URLSearchParams order
            the client builds (category, limit, slim, minCoverage) — the
            preload and the real fetch must be the SAME URL string or the
            browser fetches it twice. */}
        <link rel="preload" as="fetch" href="/api/news?category=relevant&limit=24&slim=1&minCoverage=1" crossOrigin="anonymous" fetchPriority="high" />
        {/* Preload the icon — used in the header, shown immediately on load */}
        <link rel="preload" as="image" href="/icon-192.png" fetchPriority="high" />
        {/* ── PWA launch gate — decides whether the splash plays ──
            Runs synchronously in <head>, BEFORE the first paint, so the
            decision is made before the splash element even renders.
            The splash now plays ONLY when the app is FRESHLY OPENED as an
            installed PWA:
              • display-mode standalone (or minimal-ui) — i.e. launched from
                the home screen / app drawer, NOT a normal browser tab. The
                website NEVER shows the animation.
              • NavigationTiming type === 'navigate' — a FRESH document load.
                Pull-to-refresh, F5, location.reload() and the service-
                worker-update reload are all type 'reload', and back/forward
                returns are 'back_forward' — none of them replay the splash.
            When both pass, the script adds `nw-launch` to <html>; the
            inlined splash CSS below only renders #nw-splash under that
            class. <html> already carries suppressHydrationWarning, so the
            pre-hydration class mutation is hydration-safe (same pattern as
            the theme scripts). window.__NW_LAUNCH exposes the decision for
            debugging/testing. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var standalone=false;try{standalone=window.matchMedia('(display-mode: standalone)').matches||window.matchMedia('(display-mode: minimal-ui)').matches}catch(e){}var navType='navigate';try{var navs=performance.getEntriesByType('navigation');if(navs&&navs.length&&navs[0].type)navType=navs[0].type}catch(e){}window.__NW_LAUNCH={standalone:standalone,navType:navType};if(standalone&&navType==='navigate'){document.documentElement.classList.add('nw-launch')}}catch(e){}})();`,
          }}
        />
        {/* ── PWA launch splash — full-screen tri-color animation ──
            Critical CSS, inlined so it paints with the very first HTML
            byte (no waiting for the CSS bundle). REPLACES the previous
            minimal icon splash — this is the one and only launch
            animation (nothing plays after it).

            PWA-ONLY + FRESH-OPEN-ONLY (see the launch-gate script above):
            the base rule keeps #nw-splash display:none — it only becomes
            display:flex under html.nw-launch, which the gate script sets
            exclusively for a freshly opened installed PWA. Browser tabs
            and in-app reloads (pull-to-refresh, SW-update reload, F5) and
            back/forward navigations never see it.

            The design uses NeutralWire's 3 spectrum colors — blue (left),
            grey (center), red (right):
              • Two large soft orbs (blue top-left, red bottom-right) tint
                the FULL screen and breathe in.
              • The wordmark rises in while the tri-color bar CONVERGES:
                the blue segment slides in from the left, the red segment
                from the right, and the grey center expands — they snap
                together into the balanced bias bar that is the brand.
            ALWAYS DARK (no light variant): the launch sequence is one
            continuous dark branded moment — the OS launch screen (manifest
            background_color #0a0a0a on Android, apple-touch-startup-image
            PNGs on iOS) hands off to this dark splash, which then fades
            into the app whatever its theme. A light splash variant would
            reintroduce a white flash between the dark OS launch screen and
            the app for dark users, so the splash is dark in BOTH color
            schemes now.
            HYDRATION-SAFE BY DESIGN: 100% CSS — the out-animation
            (0.32s hold + 0.16s fade, animation-fill-mode: forwards)
            retires the layer at a fixed ~480ms with ZERO JavaScript DOM
            mutation of the splash element, so React never sees an
            attribute mismatch during hydration and nothing can ever
            re-show it. The whole animation therefore never lasts more
            than half a second, on ANY connection speed. */}
        <style
          dangerouslySetInnerHTML={{
            __html: `
#nw-splash{position:fixed;inset:0;z-index:9999;display:none;overflow:hidden;background:#0a0a0a;color:#ececec;pointer-events:none}
html.nw-launch #nw-splash{display:flex;align-items:center;justify-content:center;animation:nw-splash-out .16s ease .32s forwards}
#nw-splash .nw-sp-orb{position:absolute;width:62vmax;height:62vmax;border-radius:50%;filter:blur(52px);opacity:0;animation:nw-sp-orb .34s ease-out .02s forwards}
#nw-splash .nw-sp-orb-b{top:-18vmax;left:-16vmax;background:radial-gradient(circle at 35% 35%,rgba(59,130,246,.38),rgba(59,130,246,0) 68%)}
#nw-splash .nw-sp-orb-r{bottom:-18vmax;right:-16vmax;background:radial-gradient(circle at 65% 65%,rgba(239,68,68,.34),rgba(239,68,68,0) 68%)}
#nw-splash .nw-sp-wrap{position:relative;display:flex;flex-direction:column;align-items:center;gap:16px;transform:translateZ(0)}
#nw-splash .nw-sp-word{font-family:var(--font-geist-sans),system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;font-size:26px;font-weight:800;letter-spacing:.01em;animation:nw-sp-word .28s cubic-bezier(.16,1,.3,1) both .03s}
#nw-splash .nw-sp-bar{display:flex;width:min(62vw,300px);height:12px;border-radius:99px;overflow:hidden;background:rgba(127,127,127,.16)}
#nw-splash .nw-seg{display:block;height:100%;transform:translateZ(0)}
#nw-splash .nw-seg-b{width:37%;background:#3b82f6;border-radius:99px 0 0 99px;animation:nw-seg-left .34s cubic-bezier(.18,.89,.32,1.08) both}
#nw-splash .nw-seg-g{width:26%;background:#a1a1a1;transform-origin:50% 50%;animation:nw-seg-grow .3s cubic-bezier(.16,1,.3,1) both .05s}
#nw-splash .nw-seg-r{width:37%;background:#ef4444;border-radius:0 99px 99px 0;animation:nw-seg-right .34s cubic-bezier(.18,.89,.32,1.08) both}
#nw-splash .nw-sp-tag{font-family:var(--font-geist-sans),system-ui,sans-serif;font-size:11px;font-weight:600;letter-spacing:.24em;text-transform:uppercase;opacity:0;color:#9a9a9a;animation:nw-sp-tag .24s ease both .12s}
@keyframes nw-splash-out{to{opacity:0;visibility:hidden}}
@keyframes nw-sp-orb{from{opacity:0;transform:scale(.85)}to{opacity:1;transform:scale(1)}}
@keyframes nw-sp-word{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
@keyframes nw-seg-left{from{transform:translateX(-180%)}to{transform:translateX(0)}}
@keyframes nw-seg-right{from{transform:translateX(180%)}to{transform:translateX(0)}}
@keyframes nw-seg-grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}
@keyframes nw-sp-tag{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}
@media (prefers-reduced-motion:reduce){#nw-splash .nw-sp-orb,#nw-splash .nw-sp-word,#nw-splash .nw-seg,#nw-splash .nw-sp-tag{animation:none}#nw-splash .nw-sp-orb{opacity:.5}#nw-splash .nw-seg-g{transform:none}}
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {/* ── PWA launch splash — full-screen tri-color animation ──
            Server-rendered (identical HTML for everyone → hydration is a
            no-op) but INVISIBLE by default: the CSS only displays it under
            html.nw-launch, which the head launch-gate script sets strictly
            when the app is freshly opened as an installed PWA — never in a
            browser tab, never on pull-to-refresh/reload/back-forward.
            When it does play, the PWA opens straight into the branded
            animation instead of a white screen: blue slides in from the
            left, red from the right, grey expands from the center — the
            three converge into the NeutralWire bias bar over large tinted
            screen orbs. The inlined CSS above fades the whole layer out
            and retires it (opacity 0, visibility hidden,
            animation-fill-mode: forwards) at a FIXED ~480ms — 320ms play
            + 160ms fade — so it never lasts more than half a second no
            matter how slow the connection is.
            NO JavaScript touches this element: React renders it once, the
            CSS animation handles its whole lifecycle, and nothing can
            re-show it or fight hydration. */}
        <div id="nw-splash" aria-hidden="true">
          {/* Full-screen tinted orbs — blue (left) + red (right). */}
          <div className="nw-sp-orb nw-sp-orb-b" />
          <div className="nw-sp-orb nw-sp-orb-r" />
          <div className="nw-sp-wrap">
            <div className="nw-sp-word">NeutralWire</div>
            {/* The bias bar: blue | grey | red converging into one. Plain
                <i> elements on purpose — they render identically before
                and after hydration and are driven purely by CSS. */}
            <div className="nw-sp-bar">
              <i className="nw-seg nw-seg-b" />
              <i className="nw-seg nw-seg-g" />
              <i className="nw-seg nw-seg-r" />
            </div>
            <div className="nw-sp-tag">Left · Center · Right</div>
          </div>
        </div>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
          {/* Invisible paste-triggered screen recorder (developer footage
              tool) — renders null; listens for the secretscreenrecord…
              magic words. See secret-screen-recorder.tsx. */}
          <SecretScreenRecorder />
          <Toaster />
        </ThemeProvider>
        {/* Service worker registration — required for PWA install + push notifications.
            Passes updateViaCache: 'none' so the browser ALWAYS fetches the
            latest sw.js (never a stale cached copy). Also listens for a new
            SW taking over and reloads the page so the new notification
            config (e.g. removed action buttons) takes effect immediately.
            ── v23 LOAD-TIME CHANGES ──
            1. Registration runs on requestIdleCallback (fallback: window
               load). The old 'load' listener waited for EVERY subresource
               (images, chunks) before the SW even began installing — now
               the install + precache start seconds earlier and the
               beforeinstallprompt machinery is available sooner, without
               ever competing with first paint.
            2. controllerchange no longer reloads on the FIRST takeover
               (the initial SW install claim) — that fired a pointless full
               page reload on every brand-new visitor, an entire extra
               load cycle right when we want the fastest first impression.
               Only SUBSEQUENT takeovers (real updates) reload. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                var register = function() {
                  navigator.serviceWorker.register('/sw.js', {
                    updateViaCache: 'none'  // always fetch fresh sw.js
                  }).then(
                    function(registration) {
                      // If a new SW is waiting to activate, tell it to skip
                      // waiting immediately (it already calls skipWaiting on
                      // install, but this covers the case where it's already
                      // installed but waiting).
                      if (registration.waiting) {
                        registration.waiting.postMessage({ type: 'SKIP_WAITING' });
                      }
                    },
                    function(err) {
                      console.warn('[SW] registration failed:', err);
                    }
                  );
                };
                if (window.requestIdleCallback) {
                  window.requestIdleCallback(register, { timeout: 2000 });
                } else {
                  window.addEventListener('load', register);
                }

                // Reload when a new SW takes over — but NEVER on the first
                // takeover (initial install): that reload was pure waste for
                // new visitors. After the first takeover, any subsequent
                // controllerchange is a real update → reload once.
                var hadController = !!navigator.serviceWorker.controller;
                var refreshing = false;
                navigator.serviceWorker.addEventListener('controllerchange', function() {
                  if (refreshing) return;
                  if (!hadController) {
                    hadController = true; // first takeover: just note it
                    console.log('[SW] first takeover — no reload needed');
                    return;
                  }
                  refreshing = true;
                  console.log('[SW] new controller took over — reloading');
                  window.location.reload();
                });
              }
            `,
          }}
        />
        {/* ── Firebase download tracker (DEV ONLY) ──
            Polls /api/fb-stats and logs Firebase download sizes to the
            browser console. This is a DEVELOPMENT TOOL — in production it
            was causing ~120 serverless invocations/hour per active user
            (every 30s polling), which:
              - Burned Vercel Fluid Compute CPU (4h/month limit)
              - Burned Function Invocations (104K/1M limit)
              - Each poll was a cold function call (~50ms CPU)

            Now gated behind a `?debug=fb` URL param OR
            `localStorage.debug_fb = 1`. Default: does NOT poll at all
            in production, saving ~120 invocations/hour per user. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Only run if explicitly enabled via URL param or localStorage
                var enabled = false;
                try {
                  if (window.location.search.indexOf('debug=fb') !== -1) {
                    enabled = true;
                    try { localStorage.setItem('debug_fb', '1'); } catch (e) {}
                  } else if (localStorage.getItem('debug_fb') === '1') {
                    enabled = true;
                  }
                } catch (e) {}

                if (!enabled) return;

                var sessionTotal = 0;
                var lastSessionId = null;
                var lastInstanceBytes = 0;

                function formatBytes(bytes) {
                  if (bytes < 1024) return bytes + ' B';
                  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';
                  return (bytes / 1048576).toFixed(2) + ' MB';
                }

                function poll() {
                  fetch('/api/fb-stats', { cache: 'no-store' })
                    .then(function(res) { return res.ok ? res.json() : null; })
                    .then(function(data) {
                      if (!data) return;
                      if (data.sessionId !== lastSessionId) {
                        if (lastSessionId !== null) {
                          console.log(
                            '%c[Firebase] Previous instance total: ' + formatBytes(lastInstanceBytes),
                            'color: #ff6b6b; font-weight: bold;'
                          );
                        }
                        lastSessionId = data.sessionId;
                        lastInstanceBytes = data.sessionDownloadBytes;
                        sessionTotal += data.sessionDownloadBytes;
                      } else {
                        var delta = data.sessionDownloadBytes - lastInstanceBytes;
                        if (delta > 0) {
                          sessionTotal += delta;
                          lastInstanceBytes = data.sessionDownloadBytes;
                        }
                      }
                      console.log(
                        '%c[Firebase] Session: ' + formatBytes(sessionTotal) +
                        ' | Instance: ' + formatBytes(data.sessionDownloadBytes) +
                        ' (' + data.sessionOps + ' ops)',
                        'color: #4ecdc4; font-weight: bold;'
                      );
                      if (data.recentOps && data.recentOps.length > 0) {
                        var recent = data.recentOps.slice(-5);
                        var newOps = recent.filter(function(op) {
                          return op.ts > (window.__lastFbLogTs || 0);
                        });
                        if (newOps.length > 0) {
                          console.groupCollapsed(
                            '%c[Firebase] Last ' + newOps.length + ' reads:',
                            'color: #95e1d3;'
                          );
                          newOps.forEach(function(op) {
                            console.log(
                              op.method + ' ' + op.path + ' → ' + formatBytes(op.bytes)
                            );
                          });
                          console.groupEnd();
                          window.__lastFbLogTs = newOps[newOps.length - 1].ts;
                        }
                      }
                    })
                    .catch(function() {});
                }

                console.log(
                  '%c[Firebase Tracker] DEBUG mode active. Polling every 60s. Add ?debug=fb to enable.',
                  'color: #c44569; font-weight: bold; font-size: 14px;'
                );
                // Poll every 60 seconds (was 30s — halved to reduce invocations)
                setInterval(poll, 60000);
                setTimeout(poll, 3000);
              })();
            `,
          }}
        />
        {/* Vercel Analytics — page view tracking, cookie-consent gated
            (events are dropped until "Accept all"; see analytics-gated.tsx) */}
        <GatedAnalytics />
      </body>
    </html>
  );
}
