/**
 * mesh-sign.ts — SERVER-ONLY manifest signing for the mesh relay.
 *
 * ⚠️ NEVER import this from a client component ('use client') or any
 * code path that reaches the browser bundle. The private JWK below is
 * the root of trust for mesh data integrity: the Firebase RTDB has
 * public read/write rules, so the ECDSA signature is the ONLY thing
 * that distinguishes a server-written manifest from a client forgery.
 *
 * The matching public key is embedded in mesh-crypto.ts (client-side).
 * Generated by scripts/gen-mesh-keypair.ts; the private key lives in
 * this PRIVATE repo — treat a repo leak as a key compromise (rotate by
 * re-running the generator and redeploying; clients verify with the
 * public key compiled into the bundle, so rotation ships with the
 * deploy itself).
 */

import { manifestSignPayload } from '@/lib/mesh/mesh-crypto'

const MESH_PRIVATE_JWK: JsonWebKey = {
  kty: 'EC',
  crv: 'P-256',
  x: 'OdLABW-3o2CpBXaKOPiaynwUbr40k0qsT56KUL_2t5Q',
  y: 'WoAcggr8dJE6GUjFBOfUkgnF3dGTPN8ol6RrwXDZJT0',
  d: '3SVsFyp8xgdEkCxF8d1H0Gi-moVv9OJ6NbOKJPXznIg',
  ext: true,
  key_ops: ['sign'],
}

let cachedKey: CryptoKey | null = null

async function getSignKey(): Promise<CryptoKey> {
  if (cachedKey) return cachedKey
  cachedKey = await globalThis.crypto.subtle.importKey(
    'jwk',
    MESH_PRIVATE_JWK,
    { name: 'ECDSA', namedCurve: 'P-256' },
    true,
    ['sign'],
  )
  return cachedKey
}

function bytesToB64(bytes: Uint8Array): string {
  let bin = ''
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i])
  return Buffer.from(bin, 'binary').toString('base64')
}

/**
 * Sign a mesh manifest → base64 ECDSA signature.
 * Returns '' on failure (caller skips the manifest write — the mesh
 * safely degrades to "no verification possible" → clients fall back).
 */
export async function signManifest(
  room: string,
  hash: string,
  updatedAt: number,
  v: number,
): Promise<string> {
  try {
    const key = await getSignKey()
    const data = new TextEncoder().encode(
      manifestSignPayload(room, hash, updatedAt, v),
    )
    const sig = await globalThis.crypto.subtle.sign(
      { name: 'ECDSA', hash: 'SHA-256' },
      key,
      data as unknown as ArrayBuffer,
    )
    return bytesToB64(new Uint8Array(sig))
  } catch (err) {
    console.warn('[mesh-sign] signing failed:', err)
    return ''
  }
}
